### ISSUE TITLE
Runtime errors on import

### ISSUE THREAD

**Issue by leehinde** [j-genie/4D-DebugLogReader#1]
I imported my first set of logs and got a couple of runtime errors.
![error 1](https://cloud.githubusercontent.com/assets/208609/16324598/a7cc4240-396a-11e6-918f-bc0d3b985565.png)
![error 2](https://cloud.githubusercontent.com/assets/208609/16324606/b32ab3ec-396a-11e6-84e5-e8b7d10881a1.png)
![how i figured which file to include](https://cloud.githubusercontent.com/assets/208609/16324608/b67afe3a-396a-11e6-84c6-4991b8335617.png)

[4DDebugLog_4.txt.zip](https://github.com/j-genie/4D-DebugLogReader/files/331021/4DDebugLog_4.txt.zip)

**Comment by j-genie** [comment]
Hi Lee

Seems like a memroy related issue. That log file imports fine for me.

Line 59 is 4D's Document to text function so it seems like there's not enough memory to read that log file. I suspect it may be because of the number of previous log files already imported. In order to get any kind of performance out of the import I had to parse all of the log file contents into memory first and then write them to the database at the end of the whole import process.

I've only ever imported 5 log files at a time. Perhaps you could try again just using the last 5 log files?

Alternatively you could try playing with the 4D memory settings. Also, if you're not already running 4D 64-bit you might be able to try that?

Regards
Justin

**Comment by leehinde** [comment]
yes, there were 10 files in the folder. I'll try with a smaller selection.

Thanks.

**Comment by j-genie** [comment]
Great. Good to know! :)
